SELECT YEAR(A.YM) AS YEAR, ROUND(SUM(A.PM_VAL1) / COUNT(*), 2) AS PM10, ROUND(SUM(A.PM_VAL2) / COUNT(*), 2) AS 'PM2.5'
FROM AIR_POLLUTION A 
WHERE A.LOCATION2 LIKE '수원'
GROUP BY YEAR
ORDER BY YEAR ASC;