SELECT DISTINCT B.ID AS ID, B.EMAIL AS EMAIL, B.FIRST_NAME AS FIRST_NAME, B.LAST_NAME AS LAST_NAME
FROM DEVELOPERS B JOIN (SELECT DISTINCT A.CODE CODE
FROM SKILLCODES A
WHERE A.NAME IN('Python', 'C#')) C 
WHERE B.SKILL_CODE & C.CODE != 0
ORDER BY B.ID ASC;